# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a4334113cf9bd7614b9e2cf718bc8af5d687979a600758f9e4a17c711746151ef1adfc4a0c6a26e419d8bef993d27b8e36e5f145eec1c6b93cfe8c482bdb798

test:
  secret_key_base: 0b79dbdb01ae74a6af29a4415c7af8eb6660a20b0e1a651c64cc81d2a5263a81bf3cb405e75b2efe8236e25584ee040b4bd4d4dd7244a35b3f093b1736b50009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
